version: 2
updates:
  - package-ecosystem: pip
    directory: /python_sqlite
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Dhaka
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: deps

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: Asia/Dhaka
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - security
    commit-message:
      prefix: build-deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Asia/Dhaka
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - security
    commit-message:
      prefix: actions
