version: 2
updates:
  - package-ecosystem: pip
    directory: /python_sqlite
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Dhaka
    open-pull-requests-limit: 5
    groups:
      analytics-patch-minor:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Asia/Dhaka
    open-pull-requests-limit: 3
    groups:
      actions-patch-minor:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    commit-message:
      prefix: actions
